#!/bin/bash

# Pre-clean.
rm *.snap *.pem
snapcraft clean

# Commit changes to git.
git add *
git commit -m "Deployment"
git push

# Make snap package.
snapcraft

# Upload to store.
snapcraft push *.snap > push.txt

# Readify Package.
cat push.txt > push2.txt
grep 'Revision' push2.txt > push.txt
grep -o '[0-9]' push.txt > push2.txt
$(echo snapcraft release recipe-manager `tr -d "\n\r" < push2.txt` stable)

# Post-clean.
rm push.txt push2.txt
snapcraft clean

# Install snap locally.
snap install recipe-manager
snap refresh

# Configure snap locally.
# sudo nano /root/snap/recipe-manager/current/recipe-manager/network_config.json

sudo systemctl restart snap.recipe-manager.server.service
sudo systemctl status snap.recipe-manager.server.service
